### ISSUE TITLE
API Returns None To Successful Withdrawal Request

### ISSUE THREAD

**Issue by aabraamyan** [mtusman/gemini-python#4]
I've come across an issue with api_query() in the PrivateClient class. I executed a crypto withdrawal request and the **r.json() return value** came back as **None** which then causes the loader to throw a **JSONDecodeError**.

The call however did successfully execute on Gemini. In other words, the withdrawal request was successful, but the wrapper throws an exception.

Not sure if there is anyway this can be addressed, maybe check the status code of the response before returning the JSON. This way the caller may have a better idea of what actually occurred (what error code was returned by Gemini).

The fact that the withdrawal request was successful is the really confusing part... have you guys encountered any similar issues?

**Comment by mtusman** [comment]
Hey, 

Thanks for reporting the issue. Do you mind overriding the `api_query` method with `print(r.text)` before the line `r.json` because I can't seem to replicate this error and I'll be helpful in understanding how to debug this issue?

**Comment by aabraamyan** [comment]
Haven't been able to reproduce
. Just found this on the Gemini Status page which could explain the issue "If you encounter an **error during an ETH withdrawal**, it may result in a temporary “hold” on your account balance while our Ethereum system **attempts to send your withdrawal** out to the blockchain. Please do not retry your withdrawal, as that will result in multiple transactions." https://status.gemini.com/

I'll provide more details if I can reproduce...
